all:

clean:
	@cd ClosedDatatype; make clean
	@cd OpenDatatype1; make clean
	@cd OpenDatatype2; make clean
	@cd FunctorialStyle; make clean

test:
	@cd ClosedDatatype; make test
	@cd OpenDatatype1; make test
	@cd OpenDatatype2; make test
	@cd FunctorialStyle; make test
