all:

clean:
	@cd ClosedDatatype; make clean
	@cd OpenDatatype; make clean
	@cd FeatureInteraction; make clean

test:
	@cd ClosedDatatype; make test
	@cd OpenDatatype; make test
	@cd FeatureInteraction; make test
